# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - trainings-backend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies locally (to package with app)
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          deactivate

      - name: Prepare deployment package
        run: |
          mkdir package
          cp -r app.py db.py requirements.txt utils routes email_services package/
          cp -r venv/lib/python3.12/site-packages package/
          cd package && zip -r ../app_package.zip . && cd ..

      - name: Upload deployment package
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: app_package.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download deployment package
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Deploy to Azure Web App (Run from Package)
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'trainings-backend'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_7F69CE5B4E4A47A7B587986DEF4F83A1 }}
          package: app_package.zip
